apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: store-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
